site_name: "bimdonity"
site_url: https://bimdonity.ch/
theme:
  name: material
  language: de
  logo: images/bimdo-logo.svg
  favicon: images/bimdo-logo.svg
    
  palette:
    - scheme: default        # Heller Modus (weiß)
      primary: black
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - scheme: slate          # Dunkler Modus (slate)
      primary: black
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/manemme/bimdo-wiki
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@bimdoer
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/manuel-emmenegger-45353819b/

plugins:
  - search
  - macros
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: de
          default: true
          name: Deutsch
          build: true
        - locale: fr
          name: Français
          build: true
        - locale: it
          name: Italiano
          build: true
        - locale: en
          name: English
          build: true


extra_css:
  - styles/custom.css

markdown_extensions:
  - attr_list
  - md_in_html
