site_name: "bimdonity"
site_url: https://bimdonity.ch/
theme:
  name: material
  language: de
  logo: images/bimdo-logo.svg
  favicon: images/bimdo-logo.svg
  font: false  # Disable Google Fonts completely
  
  palette:
    - scheme: default        # Heller Modus (weiß)
      primary: black
      accent: light blue
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - scheme: slate          # Dunkler Modus (slate)
      primary: black
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bimdoer/bimdonity
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@bimdoer
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/manuel-emmenegger-45353819b/
  consent:
    title: Cookie Settings
    description: >- 
      This website uses external services and hosting providers.
      These services may collect usage data according to their terms.
      Learn more in our <a href="/About/privacy-policy/" target="_blank">privacy policy</a> and <a href="/About/imprint/" target="_blank">imprint</a>.
    cookies:
      analytics:
        name: Google Analytics
        checked: false
      github:
        name: GitHub
        checked: true
plugins:
  - search
  - macros
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: de
          name: Deutsch
          build: true
        - locale: fr
          name: Français
          build: true
        - locale: it
          name: Italiano
          build: true
        - locale: en
          default: true
          name: English
          build: true
  - privacy

extra_css:
  - styles/custom.css

extra_javascript:
  - javascripts/redirect.js

markdown_extensions:
  - attr_list
  - md_in_html
