name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - main                # Trigger when changes are pushed to the 'main' branch
    paths:
      - 'docs/*'             # Trigger when any file in 'docs/' (Markdown files) changes
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check GitHub Token Permissions
        run: |
          echo "Checking GitHub Token Permissions..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/permissions \
               | jq .

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs

      - name: Build MkDocs site
        run: mkdocs build --site-dir ./site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          target_branch: gh-pages
