name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - main                # Trigger when changes are pushed to the 'main' branch
    paths:
      - 'docs/*'             # Trigger when any file in 'docs/' (Markdown files) changes
      - 'assets/**/*'        # Trigger when any file in 'assets/' (images, CSS, JS) changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs

      # Build the MkDocs site
      - name: Build MkDocs site
        run: mkdocs build --site-dir ./site

      # Deploy to GitHub Pages (or another branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
          publish_dir: ./site                           # Directory with the built MkDocs site
          target_branch: gh-pages                       # The branch to deploy to (usually `gh-pages`)
